Netflix/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path("", include("data.urls", namespace="data")),

]
urlpatterns+=static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

data/urls.py
from django.urls import path
from . import views

app_name = "data"

urlpatterns = [
    path("", views.Home.as_view(), name="home"),
    path("profiles/", views.ProfileList.as_view(), name="profiles"),
    path("create-profile/", views.ProfileCreate.as_view(), name="create-profile"),
    path("watch-list/<str:profile_id>/", views.WatchList.as_view(), name="watch-list"),
    path("movie/<str:movie_id>/", views.MovieDetail.as_view(), name="movie-details"),
    path("play/<str:movie_id>/", views.PlayVideo.as_view(), name="play"),
]

data/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
import uuid

# Create your models here.
AGE_CHOICES = (
    ("All", "All Ages"),
    ("Kids", "Kids"),
)

MOVIE_TYPES = (
    ("Series", "Series"),
    ("Single", "Single"),
)

class CustomUser(AbstractUser):
    profiles = models.ManyToManyField('Profile', null=True, blank=True)


class Profile(models.Model):
    name = models.CharField(max_length=500)
    age_limit = models.CharField(max_length=200, choices=AGE_CHOICES)
    uuid = models.UUIDField(default=uuid.uuid4)


class Movie(models.Model):
    title = models.CharField(max_length=500)
    description = models.TextField(blank=True, null=True)
    created = models.DateTimeField(auto_now_add=True)
    uuid = models.UUIDField(default=uuid.uuid4)
    type = models.CharField(max_length=200, choices=MOVIE_TYPES)
    videos = models.ManyToManyField('Video')
    flyer = models.ImageField(upload_to="flyers")
    age_limit = models.CharField(max_length=200, choices=AGE_CHOICES)


class Video(models.Model):
    title = models.CharField(max_length=200, blank=True, null=True)
    file = models.FileField(upload_to="videos")
    

data/forms.py
from django.forms import ModelForm
from . models import Profile


class ProfileCreateForm(ModelForm):
    class Meta:
        model = Profile
        exclude = ["uuid"]
        #fields = ["name", "age_limit"]

data/views.py
from django.shortcuts import render, redirect
from django.utils import timezone
from . models import CustomUser, Profile,Movie,Video
from django.views import View
from django.contrib.auth.decorators import login_required
from django.utils.decorators import method_decorator
from . forms import ProfileCreateForm
from . models import Profile
# Create your views here.
class Home(View):
    def get(self, request, *args, **kwargs):
        if request.user.is_authenticated:
            return redirect("data:profiles")
        return render(request, "index.html")


@method_decorator(login_required, name='dispatch')
class ProfileList(View):
    def get(self,request, *args, **kwargs):
        profiles = request.user.profiles.all()
        context = {
            "profiles": profiles
        }
        return render(request, "profileList.html", context)


@method_decorator(login_required, name="dispatch")
class ProfileCreate(View):
    def get(self, request, *args, **kwargs):
        #profile creation form
        form = ProfileCreateForm()

        context = {
            "form": form
        }
        return render(request, "profileCreate.html", context)

    def post(self, request, *args, **kwargs):
        form = ProfileCreateForm(request.POST or None)

        context = {
            "form": form
        }

        if form.is_valid():
            #print(form.cleaned_data)
            profile = Profile.objects.create(**form.cleaned_data)
            if profile:
                request.user.profiles.add(profile)
                return redirect("data:profiles")
        return render(request, "profileCreate.html", context)


@method_decorator(login_required, name="dispatch")
class WatchList(View):
    def get(self, request, profile_id, *args, **kwargs):
        try:
            profile = Profile.objects.get(uuid=profile_id)
            movies = Movie.objects.filter(age_limit=profile.age_limit)
            if profile not in request.user.profiles.all():
                return redirect(to="data:profiles")
            return render(request, "movieList.html", {"movies": movies})
        except Profile.DoesNotExist:
            return redirect(to="data:profiles")


@method_decorator(login_required, name="dispatch")
class MovieDetail(View):
    def get(self, request, movie_id, *args, **kwargs):
        try:
            movie = Movie.objects.get(uuid=movie_id)
            return render(request, "movieDetail.html", {"movie": movie})
        except Movie.DoesNotExist:
            return redirect("data:profiles")


@method_decorator(login_required, name="dispatch")
class PlayVideo(View):
    def get(self, request, movie_id, *args, **kwargs):
        try:
            movie = Movie.objects.get(uuid=movie_id)
            movie = movie.videos.values()

            return render(request, "showMovie.html", {"movie": movie})
        except Movie.DoesNotExist:
            return redirect("data:profiles")

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Netflix {% block title %}{% endblock title %}</title>
    <link rel="stylesheet" href="{% static 'style.css' %}">
    <script src="https://unpkg.com/ionicons@5.4.0/dist/ionicons.js"></script>
    <style>
        .player::-webkit-progress-bar{
            color: red;
        }
    </style>
</head>
<body class="bg-black text-gray-100">
    <nav class="flex justify-between items-center py-3 px-4 fixed w-full z-50">
        <div class="w-6/12">
            <img src="{% static 'netflix.png' %}" alt="logo" class="w-5/12 md:w-2/12">
        </div>

        <div>
         {% if request.user.is_authenticated %}
         <a href="/accounts/logout" class='bg-primary_red py-1 px-3 text-white md:text-lg rounded-md'>Sign Out</a>
            {% else %}
            <a href="/accounts/login" class='bg-primary_red py-1 px-3 text-white md:text-lg rounded-md'>Sign In</a>
         {% endif %}
            
        </div>
    </nav>
    {% block content %}
    
    {% endblock content %}
    <footer class=" px-5 py-10 ">
        <ul class="flex justify-between items-center">
            
            <li>&copy; 2022</li>
            <li> Made with Django and Tailwind</li>
            <li>By Paul Ndambo</li>
        </ul>
    </footer>
</body>
</html>

templates/index.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<header class="min-h-screen bg-black bg-opacity-75 showcase border-gray-600 border-b-8 flex justify-center items-center bg-no-repeat"  style="background-image: url('{% static 'background_netflix.jpg' %}');">
    <div class="z-10 h-full py-32 md:py-0 text-gray-100 text-center flex items-center flex-col">
        <h1 class="font-semibold text-4xl md:text-5xl w-10/12 md:w-3/4 text-center">
            Unlimited movies, TV shows, and more.
        </h1>
        <h3 class="text-xl md:text-xl py-5">
            Watch anywhere. Cancel anytime.
        </h3>
        <h4 class="text-sm md:text-lg pb-3">
            Ready to watch? Enter your email to create or restart your membership.
        </h4>

        <div class="w-full flex justify-center">
            <div class="flex justify-center items-center w-11/12 md:w-10/12">
                <input type="email" name="" id="" placeholder="Email address" class="md:py-5 py-4 px-2 placeholder-gray-500 rounded-tl-sm rounded-bl-sm outline-none  text-gray-900 bg-gray-50 block w-8/12 md:w-3/4">
                <button class="bg-primary_red font-medium md:font-normal md:w-1/4 flex justify-center items-center py-4 px-1 md:px-0 rounded-br-sm rounded-tr-sm md:text-2xl">
                    <span>
                        Get Started
                    </span>
                    <ion-icon name="chevron-forward-outline" class="text-2xl"></ion-icon>
                </button>
            </div>
        </div>
    </div>
</header>

<section class='flex flex-col md:flex-row items-center border-gray-900 border-b-8' style="min-height: 70vh;">
    <div class="md:w-1/2 flex flex-col justify-center text-center md:text-left p-5 md:p-10 ">
        <h2 class="md:text-5xl text-4xl font-semibold mb-4">
            Enjoy on your TV.
        </h2>
        <h5 class="md:text-xl text-lg">
            Watch on Smart TVs, Playstation, Xbox, Chromecast, Apple TV, Blu-ray players, and more.
        </h5>
    </div>
    <div class='md:w-1/2 flex justify-center items-center'>
        <img src="{% static 'tv.png' %}" class="w-8/12" alt="">
    </div>
</section>

<section class='flex flex-col md:flex-row items-center border-gray-900 border-b-8' style="min-height: 70vh;">
    <div class='md:w-1/2 flex justify-center items-center order-2'>
        <img src="static/mobile-0819.jpg" class="w-8/12" alt="">
    </div>

    <div class="md:w-1/2 flex flex-col justify-center text-center md:text-left p-5 md:p-10">
        <h2 class="md:text-5xl text-4xl font-semibold mb-4">
            Download your shows to watch offline.
        </h2>
        <h5 class="md:text-xl text-lg">
            Save your favorites easily and always have something to watch.
        </h5>
    </div>
    
</section>

<section class='flex flex-col md:flex-row items-center border-gray-900 border-b-8' style="min-height: 70vh;">
    <div class="md:w-1/2 flex flex-col justify-center text-center md:text-left p-5 md:p-10">
        <h2 class="md:text-5xl text-4xl font-semibold mb-4">
            Create profiles for kids.
        </h2>
        <h5 class="md:text-xl text-lg">
            Send kids on adventures with their favorite characters in a space made just for them—free with your membership.
        </h5>
    </div>
    <div class='md:w-1/2 flex justify-center items-center'>
        <img src="static/netflix_kid.png" class="w-8/12" alt="">
    </div>
</section>

{% endblock content %}

templates/login.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Netflix Login</title>
    <link rel="stylesheet" href="style.css">
    <script src="https://unpkg.com/ionicons@5.4.0/dist/ionicons.js"></script>
</head>
<body>
    <nav class="flex justify-between items-center py-3 px-4 fixed w-full z-50">
        <div class="w-6/12">
            <img src="assets/netflix.png" alt="logo" class="w-5/12 md:w-2/12">
        </div>

        <div>
            <button class='bg-primary_red py-1 px-3 text-white md:text-lg rounded-md'>
                Sign In 
            </button>
        </div>
    </nav>
    <header class="min-h-screen w-full bg-black bg-opacity-75 showcase border-gray-600 border-b-8 flex justify-center py-20 bg-no-repeat"  style="background-image: url('assets/background_netflix.jpg');">
        <div class="z-10 h-full py-32 md:py-0 text-gray-100 w-6/12  flex items-center flex-col">
            <form class="bg-black bg-opacity-70 py-8 px-4 w-8/12 rounded-md" >
                <h1 class="text-4xl font-semibold text-center ">
                    Log In
                </h1>
                <div class=" text-center my-4">
                    <p class="text-primary_red ">
                        Wrong credentials
                    </p>
                   
                </div>
                <div> 
                    <Label class='text-lg font-medium mb-3'>
                        Email
                    </Label>
                    <input class="p-2 bg-gray-200 rounded-sm text-gray-900 outline-none block w-full" type="email" name="email" id="id_email" placeholder="Your Email">
                </div>
                <div class='my-3'> 
                    <Label class='text-lg font-medium mb-3'>
                        Password
                    </Label>
                    <input class="p-2 bg-gray-200 rounded-sm text-gray-900 outline-none block w-full" type="password" name="password" id="id_password" placeholder="Password">
                </div>
                <div class="flex justify-center items-center">
                    <button class="py-2 px-4 bg-primary_red text-gray-100 font-medium text-lg rounded-md">
                        Log In
                    </button>
                </div>

                <div class="text-center my-4">
                    <p>
                        Do not have account <a href="/signup.html" class="text-blue-600"> Sign Up</a>
                    </p>
                </div>
            </form>
        </div>
    </header>
</body>
</html>

templates/movieDetail.html
{% extends 'base.html' %}

{% block title %}Movie-Detail{% endblock title %}
{% block content %}


    <main class='bg-primary_black min-h-screen w-full'>
        <section class="h-screen relative bg-no-repeat pb-8 pl-6 flex justify-end items-end bg-cover" style="background-image: url('{{movie.flyer.url}}');">
            <div>
                <h2 class="text-6xl font-semibold text-white my-4">
                    {{movie.title}}
                </h2>
                <p class=" w-11/12 md:w-5/12 font-medium text-white my-4">
                    Lorem ipsum dolor sit amet consectetur, adipisicing elit. Delectus repellendus odit perspiciatis nostrum culpa exercitationem quis. Ab obcaecati odio minus. Dolorum sapiente eaque, repellendus ea fugiat amet fuga libero at!
                </p>
                <div class="flex my-4">
                   <a href="{% url 'data:play' movie_id=movie.uuid %}"> 
                    <button class="flex items-center bg-white py-2 px-5 rounded-md" style="color:black;">
                        <ion-icon name="play" class="text-2xl"></ion-icon>
                        <span class="ml-3 font-medium">
                            Play
                        </span>
                    </button>
                </a>
                    
                </div>
            </div>
        </section> 
        <section class='bg-primary_black  min-h-screen flex justify-center py-10'>
            
            {% if movie.type == "Series" %}
                <div style="margin-top:2rem;margin-bottom:2rem">
                    <h2 class="text-gray-200 text-3xl font-medium">
                        Episode
                        {% for episode in movie.videos.all %}
                            <h3 class="text-lg">
                                <a href="{% url 'data:play' movie_id=movie.uuid %}?epi={{forloop.counter0}}">{{forloop.counter}} - {{episode.title}}</a>
                            </h3>
                        {% endfor %}
                    </h2>
                </div>
            {% endif %}
            
            <div class="p-8 w-10/12 relative" >
                <h2 class="text-gray-200 text-3xl font-medium">
                    Description
                </h2>
                <div class="flex justify-center  items-center min-w-full  movie_lis">
                    <p class="text-gray-100 text-lg">
                        {{movie.description}}
                    </p>
                </div>
            </div>
        </section>
        
    </main>
    <script>
        const nav = document.querySelector('nav')

        document.addEventListener("scroll",e=>{
            
            if(scrollY>200){
                nav.classList.add('bg-gray-900')
          
            }else{
                nav.classList.remove('bg-gray-900')
                
            }
        })

    </script>
    {% endblock content %}

templates/movieList.html
{% extends 'base.html' %}
{% load static %}

{% block title %}Movies List{% endblock title %}
{% block content %}
    <main class='bg-primary_black min-h-screen w-full'>
        <section class="h-screen relative bg-no-repeat pb-8 pl-6 flex justify-end items-end bg-cover" style="background-image: url('{% static 'vikings.jpg' %}');">
            <div>
                <h2 class="text-6xl font-semibold text-white my-4">
                    Vikings
                </h2>
                <p class=" w-11/12 md:w-5/12 font-medium text-white my-4">
                    Lorem ipsum dolor sit amet consectetur, adipisicing elit. Delectus repellendus odit perspiciatis nostrum culpa exercitationem quis. Ab obcaecati odio minus. Dolorum sapiente eaque, repellendus ea fugiat amet fuga libero at!
                </p>
                <div class="flex my-4">

                    <button class="flex items-center bg-white py-2 px-5 rounded-md" style="color:black;">
                        <ion-icon name="play" class="text-2xl"></ion-icon>
                        <span class="ml-3 font-medium">
                            Play
                        </span>
                    </button>
    
                    <button class="ml-4 text-white flex items-center bg-gray-500 bg-opacity-80 py-2 px-5 rounded-md">
                       
                        <ion-icon name="information-circle-outline" class="text-2xl" ></ion-icon>
                        <a href="#">
                        <span class="ml-3 font-medium">
                            More Info
                        </span>
                    </a>
                    </button>
                </div>
            </div>
        </section> 
        <section class='bg-primary_black  min-h-screen flex justify-center py-10'>
            <div class="p-8 w-10/12 relative" >
                <h2 class="text-gray-200 text-2xl font-medium">
                    Popular on Netflix
                </h2>


                <div class="flex justify-center  items-center min-w-full  movie_lis">
                   
                    {% for movie in movies %}
                    <a href="{% url 'data:movie-details' movie.uuid %}">
                    <div class="flex-shrink-0  h-40 m-4  bg-blue-500 rounded-md cursor-pointer overflow-hidden w-40" >
                        <img src="{{movie.flyer.url}}" class="w-full h-full " alt="">
                    </div>
                </a>
                    {% endfor %}
                
                </div>
            </div>
        </section>
        
    </main>
{% endblock content %}

templates/profileCreate.html
{% extends 'base.html' %}
{% load static %}
{% block title %}Create Profile{% endblock title %}
{% block content %}
    <section class='bg-primary_black min-h-screen py-20 md:py-32 flex-col flex items-center'>
        <div class="flex flex-wrap justify-center  w-10/12  md:w-6/12">
            <form method="POST" class="w-full md:w-8/12 bg-gray-900 p-5 rounded-lg">
                
                <h1 class="text-4xl text-center text-gray-100 font-medium">
                    Create A Profile
                </h1>
                {% csrf_token %}
                <div class="my-4"> 
                    <Label class='text-lg text-gray-200 font-medium mb-3'>
                        Profile Name
                    </Label>
                    <input required class="p-2 bg-gray-500 rounded-sm text-gray-200 outline-none block w-full" type="text" name="name" id="id_name" placeholder="Profile name">
                </div>
                <div class="my-4"> 
                    <Label class='text-lg text-gray-200 font-medium mb-3'>
                        Maturity Level
                    </Label>
                    <select class="p-2 bg-gray-500 rounded-sm text-gray-200 outline-none block w-full"  name="age_limit" id="id_age_limit" >
                        <option value="All">All</option>
                        <option value="Kids">Kids</option>
                       
                    </select>
                </div>
                <div class="flex justify-center items-center">
                    <button class="px-4 py-2 rounded-md outline-none bg-primary_red text-gray-100">Create Profile</button>
                </div>
            </form> 
        </div>
        
    </section>
    {% endblock content %}

templates/profileList.html
{% extends 'base.html' %}
{% load static %}

{% block title %}
Profiles
{% endblock title %}

{% block content %}

    <section class='bg-primary_black min-h-screen py-20 md:py-0 flex-col flex justify-center items-center'>
        <h2 class="text-center font-medium text-5xl my-4 text-gray-100">
            Who's watching ?
        </h2>

        <div class="flex flex-wrap justify-center items-center w-10/12  md:w-6/12">
           
           {% for profile in profiles %}

           <a href="{% url 'data:watch-list' profile_id=profile.uuid %}">
            <div class="w-32 h-32 m-4 flex flex-col justify-center align-center text-center bg-blue-500 rounded-md cursor-pointer">
                <p class="text-6xl">
                    {{profile.name | slice:":1"}}
                </p>
                <p class="text-lg">
                    {{profile.name}}
                </p>
            </div>
           </a>
            
            {% endfor %}
        </div>
        <div class="flex justify-center items-center">
            <a href="{% url 'data:create-profile' %}"
            <button class="px-4 py-2 rounded-md outline-none bg-gray-400 text-gray-100">
                Add A New Profile
            </button>
        </a>
        </div>
    </section>
    {% endblock content %}

templates/showMovie.html
{% extends 'base.html' %}
{% block title %}Movie{% endblock title %}

{% block content %}
<body class='font-primary'>
    <main class='bg-primary_black h-full w-full '>
        
        <video src="assets/test.mp4" controls class="w-full h-screen player"></video>
        
    </main>

{% endblock content %}

templates/signup.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Netflix Sign Up</title>
    <link rel="stylesheet" href="style.css">
    <script src="https://unpkg.com/ionicons@5.4.0/dist/ionicons.js"></script>
</head>
<body>
    <nav class="flex justify-between items-center py-3 px-4 fixed w-full z-50">
        <div class="w-6/12">
            <img src="assets/netflix.png" alt="logo" class="w-5/12 md:w-2/12">
        </div>

        <div>
            <button class='bg-primary_red py-1 px-3 text-white md:text-lg rounded-md'>
                Sign In 
            </button>
        </div>
    </nav>
    <header class="min-h-screen w-full bg-black bg-opacity-75 showcase relative border-gray-600 border-b-8 flex justify-center py-20 bg-no-repeat"  style="background-image: url('assets/background_netflix.jpg');">
        <div class="z-10 min-h-full py-32 md:py-0 text-gray-100 w-6/12  flex items-center flex-col">
            <form class="bg-black bg-opacity-70 min-h-full py-8 px-4 w-8/12 rounded-md" >
                <h1 class="text-4xl font-semibold text-center ">
                    Sign Up
                </h1>
                <div class=" text-center my-4">
                    <p class="text-primary_red ">
                        Email already in use
                    </p>
                    <p class="text-primary_red ">
                        Password must be greater than 8 characters
                    </p>
                </div>
                <div> 
                    <Label class='text-lg font-medium mb-3'>
                        Email
                    </Label>
                    <input class="p-2 bg-gray-200 rounded-sm text-gray-900 outline-none block w-full" type="email" name="email" id="id_email" placeholder="Your Email">
                </div>
                <div class='my-3'> 
                    <Label class='text-lg font-medium mb-3'>
                        Password
                    </Label>
                    <input class="p-2 bg-gray-200 rounded-sm text-gray-900 outline-none block w-full" type="password" name="password" id="id_password" placeholder="Password">
                </div>
                <div class='my-3'> 
                    <Label class='text-lg font-medium mb-3'>
                        Confirm Password
                    </Label>
                    <input class="p-2 bg-gray-200 rounded-sm text-gray-900 outline-none block w-full" type="password" name="password2" id="id_password2" placeholder="Password">
                </div>
                <div class="flex justify-center items-center">
                    <button class="py-2 px-4 bg-primary_red text-gray-100 font-medium text-lg rounded-md">
                        Sign Up
                    </button>
                </div>

                <div class="text-center mt-4">
                    <p>
                        Have account already ? <a href="/signup.html" class="text-blue-600"> Log In</a>
                    </p>
                </div>
            </form>
        </div>
    </header>
</body>
</html>